baseURL = "http://foxriver.cz/"
languageCode = "cs-cz"
title = "Fox River | Chovatelská stanice"
theme = "hugo-initio"
publishDir = "build"

[params]
    name = "Fox River"
    description = "Chovatelská stanice"
    email = "bekovajana@seznam.cz"
    year = 2017
    background = ""
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = true
    showNews = true
    showRecentWorks = true
    showDownload = true
    showClients = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Naši psi"
    identifier = "nasi-psi"
    url = "/nasi-psi/"
    weight = 5

[[menu.main]]
    name = "Vzpomínáme"
    identifier = "vzpominame"
    url = "/vzpominame/"
    weight = 6

[params.google.analytics]
    trackerID = "UA-52295302-2"
